---
title: "housingdata"
output: html_document
date: "2025-12-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
```

```{r}

tidyhousingprices <- housingprices %>%
  pivot_longer(
    cols = -Mon.Yr,
    names_to = "County",
    values_to = "Value"
  ) %>%
  pivot_wider(
    names_from = Mon.Yr,
    values_from = Value
  )

tidyhousingprices <- read.csv("EditedMedianHousingPrices.csv", check.names = FALSE)
new_names <- as.character(tidyhousingprices[1, ])

# Assign them as column names
names(tidyhousingprices) <- new_names
tidyhousingprices <- tidyhousingprices[-1, ]
names(tidyhousingprices)[1] <- "Month"

rownames(tidyhousingprices) <- NULL

df_t <- tidyhousingprices %>% 
  tibble::column_to_rownames("Month")  # use Month as rownames before transpose

df_t <- as.data.frame(t(df_t))

names(df_t) <- gsub("-", "_", names(df_t))
df_t_filtered <- df_t %>% 
  select(matches("_(0[0-9]|1[0-9]|2[0-5])$"))
df_t_filtered <- df_t_filtered[!rownames(df_t_filtered) %in% c("CA", "NA", "LA Metro", 
                                              "Central Valley", "Central Coast",
                                              "Far North", "Inland Empire",
                                              "S.F. Bay Area", "SoCal"), ]

```
```{r}
afford_housing <- LIHTCPUB %>%
  filter(V5 == "CA") %>%
  select(V2,V3,V4,V5,V6,V8,V9,V22,V23,V35,V36,V61,V62,V63,V64,V65,V66,V68,V73)

afford_housing <- afford_housing %>%
  rename(project = V2,
         proj_add = V3,
         proj_city = V4,
         proj_st = V5,
         proj_zip = V6,
         latitude = V8,
         longitude = V9,
         allocamt = V22,
         N_units = V23,
         Yr_pis = V35,
         Yr_alloc = V36,
         trgt_pop = V61,
         trgt_fam = V62,
         trgt_eld = V63,
         trgt_dis = V64,
         trgt_hml = V65,
         trgt_oth = V66,
         type = V68,
         DDA = V73)

afford_housing <- afford_housing %>%
  filter(Yr_alloc >= '2000',
         Yr_alloc != '8888',
         Yr_alloc != '9999')

afford_housing$latitude  <- as.numeric(afford_housing$latitude)
afford_housing$longitude <- as.numeric(afford_housing$longitude)

library(sf)

afford_housing_clean <- afford_housing %>%
  filter(!is.na(longitude), !is.na(latitude))

afford_sf <- st_as_sf(
  afford_housing_clean,
  coords = c("longitude", "latitude"),
  crs = 4326
)
st_write(afford_sf, "affordable_housing.gpkg")

```
```{r}
colnames(zhvi_single) <- as.character(unlist(zhvi_single[1, ]))
zhvi_single <- zhvi_single[-1, ]  # remove the first row

zhvi_single <- zhvi_single %>%
  filter(State == "CA")

zhvi_single_long <- zhvi_single %>%
  pivot_longer(
    cols = matches("^\\d{4}-\\d{2}-\\d{2}$"), 
    names_to = "date",
    values_to = "price"
  ) %>%
  mutate(
    date = ymd(date),
    ZIP  = RegionName     # optional rename for QGIS clarity
  )
zhvi_single_long <- zhvi_single_long %>%
  select(-RegionID, -RegionType, -StateName, -SizeRank, -ZIP)

  zhvi_single_long <- zhvi_single_long %>%
  rename(Zip = RegionName)
  
zhvi_single_long$price <- as.numeric(zhvi_single_long$price)
zhvi_single_long$price <- round(zhvi_single_long$price, 2)

write.csv(zhvi_single_long, "zhvi_single_zip.csv", row.names = FALSE)


```


